import { OrganSystemsData } from './types';

export const organSystemsData: OrganSystemsData = {
    essentials: {
        eyebrow: 'Comprehensive Body Support',
        title: '9 Major Organ Systems',
        subtitle: 'One serving delivers comprehensive support for your entire body, replacing multiple supplements with a single, powerful formula.',
        systems: [
            {
                id: 'digestive',
                index: 0,
                number: '01',
                label: 'Digestive',
                title: 'Digestive Support',
                ingredients: 'Prebiotics, Probiotics, Postbiotics, Enzymes',
                description: 'A complete 4-tier digestive support system featuring 10 Billion CFU of probiotics and clinically proven enzymes to optimize nutrient absorption and gut health.',
                icon: 'digestive',
            },
            {
                id: 'immune',
                index: 1,
                number: '02',
                label: 'Immune',
                title: 'Immune Support',
                ingredients: 'Vit C, D, Zinc, Mushrooms',
                description: 'Fortifies your body\'s natural defenses with high-potency Vitamin C (1000% DV), Zinc, and a specialized mushroom complex including Reishi and Chaga.',
                icon: 'immune',
            },
            {
                id: 'cardiovascular',
                index: 2,
                number: '03',
                label: 'Cardiovascular',
                title: 'Cardiovascular Support',
                ingredients: 'COQ10, NITRATES, POTASSIUM',
                description: 'Supports heart health and circulation with natural nitrates from beetroot, CoQ10 for cellular energy, and potassium for healthy blood pressure levels.',
                icon: 'cardiovascular',
            },
            {
                id: 'muscular',
                index: 3,
                number: '04',
                label: 'Muscular',
                title: 'Muscular Support',
                ingredients: 'Aminos, MSM, Electrolytes',
                description: 'Accelerates recovery and maintains muscle function with a full spectrum of amino acids, MSM for joint comfort, and essential electrolytes.',
                icon: 'muscular',
            },
            {
                id: 'skeletal',
                index: 4,
                number: '05',
                label: 'Skeletal',
                title: 'Skeletal Support',
                ingredients: 'Calcium, Vit D, K2, Boron',
                description: 'Builds and maintains strong bones with bioavailable Calcium, Vitamin D3 from vegan lichen, and Vitamin K2 to direct calcium to where it\'s needed.',
                icon: 'skeletal',
            },
            {
                id: 'integumentary',
                index: 5,
                number: '06',
                label: 'Integumentary',
                title: 'Skin, Hair & Nail Support',
                ingredients: 'MSM, Vit C, E, Biotin, Silica',
                description: 'Promotes radiant skin, hair, and nails through collagen-supporting Vitamin C, Biotin, and MSM to combat oxidative stress.',
                icon: 'integumentary',
            },
            {
                id: 'nervous',
                index: 6,
                number: '07',
                label: 'Nervous',
                title: 'Nervous System Support',
                ingredients: 'B-Vitamins, Magnesium, Adaptogens',
                description: 'Calms the mind and supports cognitive function with a complete B-Complex (including Methylcobalamin) and stress-adapting herbs like Reishi & Ashwagandha.',
                icon: 'nervous',
            },
            {
                id: 'endocrine',
                index: 7,
                number: '08',
                label: 'Endocrine',
                title: 'Endocrine Support',
                ingredients: 'Adaptogens, Vit D, Chromium',
                description: 'Balances hormones and metabolism with targeted adaptogens and Chromium to support healthy blood sugar levels already within normal range.',
                icon: 'endocrine',
            },
            {
                id: 'urinary',
                index: 8,
                number: '09',
                label: 'Urinary',
                title: 'Urinary Support',
                ingredients: 'Hydra Electrolytes Complex',
                description: 'Optimizes fluid balance and kidney function with a precision hydration complex featuring Potassium Citrate and Magnesium Glycinate.',
                icon: 'urinary',
            },
        ],
    },
    longevity: {
        eyebrow: 'Advanced Cellular Science',
        title: 'Cellular Health Redefined',
        subtitle: 'A breakthrough formula targeting the 12 hallmarks of aging to help you live better, longer.',
        systems: [
            {
                id: 'cellular-cleansing',
                index: 0,
                number: '01',
                label: 'Activates Cellular Cleansing',
                title: 'Cellular Cleansing Support',
                ingredients: 'AUTOPHAGY ACTIVATION',
                description: 'Activates the body\'s natural cellular cleanup process (autophagy) to remove damaged components and improve cellular efficiency.',
                icon: 'cellular',
            },
            {
                id: 'cellular-renewal',
                index: 1,
                number: '02',
                label: 'Promotes Cellular Renewal',
                title: 'Cellular Renewal Support',
                ingredients: 'Regeneration Support',
                description: 'Promotes the regeneration of healthy cells and tissues, supporting the body\'s ability to repair and maintain itself over time.',
                icon: 'cellular',
            },
            {
                id: 'cellular-aging',
                index: 2,
                number: '03',
                label: 'Slows Cellular Aging',
                title: 'Cellular Aging Support',
                ingredients: 'Telomere Support',
                description: 'Targets the biological mechanisms of aging to help slow down cellular degradation and maintain youthful function.',
                icon: 'telomere',
            },
            {
                id: 'youthful-aging',
                index: 3,
                number: '04',
                label: 'Aids Youthful Aging',
                title: 'Youthful Aging Support',
                ingredients: 'Resilience & Vitality',
                description: 'Supports overall vitality and resilience, helping you maintain energy, focus, and physical capability as you age.',
                icon: 'cellular',
            },
        ],
    },
};
